const quests = [
 {
   "ID": 1,
   "Task": "Close unused tabs on your computer",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 2,
   "Task": "Give Bonnie a cuddle and say I love you",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 3,
   "Task": "Put on lip balm",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 4,
   "Task": "Look out the window and describe what you see",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 5,
   "Task": "Let your shoulders drop",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 6,
   "Task": "Drink a glass of water",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 7,
   "Task": "Light a candle or turn on a lamp",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 8,
   "Task": "Take a photo of something pretty",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 9,
   "Task": "Breathe in through your nose for 4 hold for 4 out for 4",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 10,
   "Task": "Tidy your desk for 2 minutes",
   "Category": "Chores",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 11,
   "Task": "Put on face mask",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 12,
   "Task": "Take 5 deep breaths",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 13,
   "Task": "Unsubscribe from one spam email",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 14,
   "Task": "Thank your body for getting you through the day",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 15,
   "Task": "Take one supplement or medication",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 16,
   "Task": "Write down something that's bothering you",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 17,
   "Task": "Delete one old photo or file",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 18,
   "Task": "Close your eyes for 10 seconds",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 19,
   "Task": "High five yourself in the mirror",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 20,
   "Task": "Wash your face",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 21,
   "Task": "Say one kind thing to yourself",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 22,
   "Task": "Set a one-word intention for the day",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 23,
   "Task": "Stretch for 30 seconds",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 24,
   "Task": "Put on cozy socks or slippers",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 25,
   "Task": "Say thank you to someone (or yourself)",
   "Category": "Relationships",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 26,
   "Task": "Wipe down a surface",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 27,
   "Task": "Look at the sky for 30 seconds",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 28,
   "Task": "Wash one Bonnie's bowl",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 29,
   "Task": "Let yourself rest without guilt for 5 mins",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 30,
   "Task": "Water one plant or just look at it",
   "Category": "Chores",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 31,
   "Task": "Give your laptop a quick dust",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 32,
   "Task": "Brush your teeth",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 33,
   "Task": "Sit up straight for 1 minute",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 34,
   "Task": "Do one small thing on your to-do list",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 35,
   "Task": "Tell a friend you appriciate them",
   "Category": "Relationships",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 36,
   "Task": "Reply to one message you've been avoiding",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 37,
   "Task": "Compliment Bonnie",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 38,
   "Task": "Change into clean clothes",
   "Category": "Chores",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 39,
   "Task": "Put one dish into the dishwasher",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 40,
   "Task": "Say one thing you're grateful for",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 41,
   "Task": "Put away one piece of laundry",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 42,
   "Task": "Wipe your phone screen",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 43,
   "Task": "Throw away a piece of trash",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 44,
   "Task": "Put away one item that's out of place",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 45,
   "Task": "Say 'I did enough today' out loud",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 46,
   "Task": "Stand up and shake your arms",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 47,
   "Task": "Check in with your posture",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 48,
   "Task": "Take a shower",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 49,
   "Task": "Write a one-word journal entry",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 50,
   "Task": "Sit on the balcony for a minute with Bonnie",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 51,
   "Task": "Do one thing more slowly on purpose",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 52,
   "Task": "Say “today is a new chance” out loud",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 53,
   "Task": "Doublecheck list of all Bonnie's commands",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 54,
   "Task": "Put your phone down and blink at the wall for 30 sec",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 55,
   "Task": "Give yourself manicure",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 56,
   "Task": "Make a nice cup of tea",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 57,
   "Task": "Make your bed",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 58,
   "Task": "Turn on music you like",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": true,
 },
 {
   "ID": 59,
   "Task": "Make homemade ice cream",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": true,
 },
 {
   "ID": 60,
   "Task": "Talk to one new person",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 61,
   "Task": "Clean the bathroom sink and mirror",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 62,
   "Task": "Write a compliment to yourself and Robin",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 63,
   "Task": "Try 3 breathing box cycles (4-4-4-4)",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 64,
   "Task": "Do a 2-minute plank",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 65,
   "Task": "Meet with a stranger",
   "Category": "Relationships",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 66,
   "Task": "Do Bonnie’s nails or check her paws",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 67,
   "Task": "Do a silent hour – no talking or audio",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 68,
   "Task": "Clean your keyboard and mouse",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 69,
   "Task": "Put one thing back in place",
   "Category": "Chores",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 70,
   "Task": "Write 3 activities you want to do - no matter money",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 71,
   "Task": "Go to bed 30 minutes earlier than usual",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 72,
   "Task": "Do 20 jumping jacks",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 73,
   "Task": "Delete unused apps on your phone",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 74,
   "Task": "Do laundry from start to finish (including folding)",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 75,
   "Task": "Clean out your fridge",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 76,
   "Task": "Take care of your hair",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 77,
   "Task": "Do 5 sun salutations",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 78,
   "Task": "Organize one kitchen cabinet",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 79,
   "Task": "Do a task without multitasking (just one thing)",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 80,
   "Task": "Take 5000 steps",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 81,
   "Task": "Update your CV",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 82,
   "Task": "Go for a 30-minute walk with Bonnie",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 83,
   "Task": "Do 15 minutes of focused cleaning",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 84,
   "Task": "Spend 15 mins working on a creative idea",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 85,
   "Task": "Play with Bonnie actively for 10 minutes",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 86,
   "Task": "Make a list of companies to work for",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 87,
   "Task": "Clean the stove top",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 88,
   "Task": "Try a new tea or drink",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 89,
   "Task": "Declutter one shelf of books or papers",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 90,
   "Task": "Find one affirmation and say it 3 times",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 91,
   "Task": "Clean mirrors",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 92,
   "Task": "Clean and organize Bonnie’s food area",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 93,
   "Task": "Vacuum the apartment",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 94,
   "Task": "Clean up your browser bookmarks",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 95,
   "Task": "Write one page in your journal",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 96,
   "Task": "Create a mood board for your dream life",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 97,
   "Task": "Send a positive comment on social media",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 98,
   "Task": "Go for a short run or jog with Bonnie",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 99,
   "Task": "Organize or plan a trip you want to take someday",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 100,
   "Task": "Sort and recycle glass, cardboard, plastic",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 101,
   "Task": "Join a running competition",
   "Category": "Fitness",
   "Time": 3,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 102,
   "Task": "Create a playlist for relaxing or focusing",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 103,
   "Task": "Write down 3 goals you want to finish before you're 30",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 104,
   "Task": "Do a yoga flow focused on hips or shoulders",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 105,
   "Task": "Watch 1 Scrimba lesson or frontend tutorial",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 106,
   "Task": "Do 10 minutes of stretching",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 107,
   "Task": "Watch one video about any IT topic",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 108,
   "Task": "Drink 2L water in a day",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 109,
   "Task": "Pet Bonnie and describe 3 things you love about her",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 110,
   "Task": "Update your programming portfolio",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 111,
   "Task": "Make a smoothie",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 112,
   "Task": "Work on your programming project for 15 minutes",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 113,
   "Task": "Clean the dishes",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 114,
   "Task": "Vacuum under the bed",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 115,
   "Task": "Spend 15 mins working on your dog food calculator",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 116,
   "Task": "Organize your desktop files or folders",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 117,
   "Task": "Clean Bonnie's paws after walk",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 118,
   "Task": "Declutter 5 items you no longer use",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 119,
   "Task": "Change Bonnie’s water",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 120,
   "Task": "Write an “I’m proud of myself for…” list",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 121,
   "Task": "Do a 10-minute yoga session",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 122,
   "Task": "Do 5 push-ups (any variation)",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 123,
   "Task": "Write or update your to-do list",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 124,
   "Task": "Clean your shower or tub",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 125,
   "Task": "Do one section of a frontend course",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 126,
   "Task": "Brush Bonnie",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 127,
   "Task": "Make a healthy snack for you and Robin",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 128,
   "Task": "Make infused water",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 129,
   "Task": "Organize Bonnie's toys",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 130,
   "Task": "Test Bonnie with a new command",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 131,
   "Task": "Do 10 air squats",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 132,
   "Task": "Revisit one of your 365 tasks and reflect",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 133,
   "Task": "Clean the toilet",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 134,
   "Task": "Try a new React hook or feature",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 135,
   "Task": "Write down 3 things you're grateful for",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 136,
   "Task": "Put away all dry dishes or unload dishwasher",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 137,
   "Task": "Rewatch a favorite feel-good movie or show scene",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 138,
   "Task": "Clean microwave",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 139,
   "Task": "Do a “screen-free” hour",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 140,
   "Task": "Walk a different route with Bonnie",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 141,
   "Task": "Update your GitHub with a new repo",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 142,
   "Task": "Buy Bonnie treat in a dog shop",
   "Category": "Dog",
   "Time": 4,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 143,
   "Task": "Pick 1 project from your to-do list and break it down",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 144,
   "Task": "Find one frontend job you could apply to",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 145,
   "Task": "Choose an outfit you feel confident in",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 146,
   "Task": "Look up a new JS concept and explain it to yourself",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 147,
   "Task": "Do 3 pullups ",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 148,
   "Task": "Write a letter to your future self",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 149,
   "Task": "Prepare 'trail mix' for Bonnie",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 150,
   "Task": "Give Robin a random compliment or hug",
   "Category": "Relationships",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 151,
   "Task": "Make a list of 5 calming things to do when anxious",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 152,
   "Task": "Spend 15 minutes reading a book",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 153,
   "Task": "Meditate for 2 minutes",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 154,
   "Task": "Refill or update your Notion dashboard",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 155,
   "Task": "Take Bonnie swimming",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": true,
 },
 {
   "ID": 156,
   "Task": "Make one project with Sanity",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 157,
   "Task": "Practice a programming exercise for 20 minutes",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 158,
   "Task": "Rewatch a programming concept you struggled with",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 159,
   "Task": "Water all your plants",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 160,
   "Task": "Plan a date idea for you and Robin",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 161,
   "Task": "Stretch for 5 minutes",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 162,
   "Task": "Do a short Bonnie training session (5 min)",
   "Category": "Dog",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": true,
 },
 {
   "ID": 163,
   "Task": "Put on humidifier",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 164,
   "Task": "Draw or doodle for 5 minutes",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 165,
   "Task": "Write 3 nice things about your current self",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": true,
 },
 {
   "ID": 166,
   "Task": "Try a body scan meditation",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 167,
   "Task": "Chill with Bonnie outside on the grass",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 168,
   "Task": "Write a short story or reflection piece about your life",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 169,
   "Task": "Try meditating for 10 full minutes",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 170,
   "Task": "Watch a documentary",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 171,
   "Task": "Send a message to a recruiter",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 172,
   "Task": "Wake up before 7 AM on purpose",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 173,
   "Task": "Write a letter to your younger self",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 174,
   "Task": "Try a recipe from a different culture",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 175,
   "Task": "Do a 20-min deep breathing practice",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 176,
   "Task": "Spend 1 hour in total silence (no input)",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 177,
   "Task": "Help a stranger (carry something, hold door)",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 178,
   "Task": "Read a book on balcony",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 179,
   "Task": "Walk Bonnie without checking your phone",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 180,
   "Task": "Teach Bonnie a new trick or command",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 181,
   "Task": "Go 1 full day without sugar or snacks",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 182,
   "Task": "Set a 2-hour creative sprint for any personal project",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 183,
   "Task": "Pick up clatter for 5 minutes",
   "Category": "Chores",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 184,
   "Task": "Run or jog for 4km",
   "Category": "Fitness",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 185,
   "Task": "Spend a day without complaining",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 186,
   "Task": "Do 3x10 push-ups throughout the day",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 187,
   "Task": "Wash all Bonnies stuff (bowls, toys, blanket)",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 188,
   "Task": "Research and plan 1 weekend getaway",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 189,
   "Task": "Walk barefoot outside (grass, beach)",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 190,
   "Task": "Take Bonnie on a bus or tram to a new area",
   "Category": "Dog",
   "Time": 5,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 191,
   "Task": "Clean all windows in your apartment",
   "Category": "Chores",
   "Time": 5,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 192,
   "Task": "Write about your biggest fear",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 193,
   "Task": "Practice Bonnie’s recall in a new environment",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 194,
   "Task": "Write a love note to Robin and hide it",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 195,
   "Task": "Reach out to someone you lost contact with",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 196,
   "Task": "Solve few challenges in JS",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 197,
   "Task": "Cook and prep lunch for the next 2 days",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 198,
   "Task": "Spend 1 hour focused on deep cleaning one room",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 199,
   "Task": "Wear something bold that makes you feel strong",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 200,
   "Task": "Plan a surprise for Robin",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 201,
   "Task": "Wash all blankets",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 202,
   "Task": "Go to a new dog park or walk route",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 203,
   "Task": "Create a small digital product (cheat sheet, planner)",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 204,
   "Task": "Take a cold shower or cold face rinse",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 205,
   "Task": "Design something small in Figma or Canva",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 206,
   "Task": "Do meal prep for breakfast",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 207,
   "Task": "Say one honest thing you're proud of",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 208,
   "Task": "Try coding in a public place",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 209,
   "Task": "Do a Calimove workout",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 210,
   "Task": "Run or jog for 2 km",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 211,
   "Task": "Organize your email inbox",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 212,
   "Task": "Set a timer for 90 minutes and clean",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 213,
   "Task": "Complete a difficult programming challenge from a course",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 214,
   "Task": "Do a body scan meditation",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 215,
   "Task": "Sit in silence for 20 minutes (no music, nothing)",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 216,
   "Task": "Do 5 pullups",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 217,
   "Task": "Go through every drawer in one room and declutter",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 218,
   "Task": "Clean the bathroom thoroughly",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 219,
   "Task": "Do 30 minutes of uninterrupted coding",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 220,
   "Task": "Spend 45 minutes on frontend development",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 221,
   "Task": "Deep clean the kitchen (sink, counters, stove)",
   "Category": "Chores",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 222,
   "Task": "Invite someone to hang out (even just a walk)",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 223,
   "Task": "Plan and go on a “solo date” in your city",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 224,
   "Task": "Write a full blog post or journal entry",
   "Category": "Mental health",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 225,
   "Task": "Build end-to end project",
   "Category": "IT",
   "Time": 5,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 226,
   "Task": "Update your LinkedIn",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 227,
   "Task": "Declutter a full shelf, box, or drawer",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 228,
   "Task": "Research a topic you find intimidating",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 229,
   "Task": "Go to a café and work for 1 hour",
   "Category": "Other",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 230,
   "Task": "Spend a full hour learning one new tech concept",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 231,
   "Task": "Add 1 new features to your portfolio site",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 232,
   "Task": "Try mirror affirmations for 3 days straight",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 233,
   "Task": "Take Bonnie on a hike or trail walk",
   "Category": "Dog",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 234,
   "Task": "Plan your week with time blocks",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 235,
   "Task": "Walk Bonnie before 8 AM",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 236,
   "Task": "Try mindfulness during a chore (e.g. dishes)",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 237,
   "Task": "Take Bonnie for a 1.5 hour sniff walk",
   "Category": "Dog",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 238,
   "Task": "Put on hand cream",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 239,
   "Task": "Create a GitHub README for a project",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 240,
   "Task": "Make a weekly meal plan & grocery list",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 241,
   "Task": "Follow a stretching routine for 30 minutes",
   "Category": "Fitness",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 242,
   "Task": "Wear an outfit that feels totally new for you",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 243,
   "Task": "Clean the oven",
   "Category": "Chores",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 244,
   "Task": "Practise riding bike together",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 245,
   "Task": "Plan a week of dinners in advance and stick to it",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 246,
   "Task": "Do a mini photo shoot with Bonnie",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 247,
   "Task": "Ask for feedback on something you’ve made",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 248,
   "Task": "Go to a library or co-working space",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 249,
   "Task": "Take Bonnie on a boat ride",
   "Category": "Dog",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 250,
   "Task": "Turn on your favourite song",
   "Category": "Self care",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 251,
   "Task": "Cook a brand-new dinner recipe",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 252,
   "Task": "Cook something together with Robin",
   "Category": "Relationships",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 253,
   "Task": "Clear out and delete unused digital files/folders",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 254,
   "Task": "Do a short guided journaling session",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 255,
   "Task": "Do a full 1-hour focus session on a project",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 256,
   "Task": "Do a “no TV” day and find other ways to relax",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 257,
   "Task": "Do 5 pistol squats",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 258,
   "Task": "Do a 30-minute yoga session",
   "Category": "Fitness",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 259,
   "Task": "Reach out to someone in your network professionally",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 260,
   "Task": "Plan a full-day adventure with Bonnie",
   "Category": "Dog",
   "Time": 5,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 261,
   "Task": "Fast until lunch",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 262,
   "Task": "Revisit your CV and apply for one role",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 263,
   "Task": "Try going to bed at 9 PM just once",
   "Category": "Self care",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 264,
   "Task": "Fix something that’s been broken for weeks",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 265,
   "Task": "Leave a kind note for someone anonymously",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 266,
   "Task": "Sort one type of clothes and donate one bag",
   "Category": "Other",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 267,
   "Task": "Do 5 push ups on fingers",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 268,
   "Task": "Wake up and do yoga first thing",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 269,
   "Task": "Code something from scratch",
   "Category": "IT",
   "Time": 4,
   "Difficulty": "Challenging",
   "Status": true,
 },
 {
   "ID": 270,
   "Task": "Do 30 second wall sit",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 271,
   "Task": "Reach out to someone you admire and ask a question",
   "Category": "Relationships",
   "Time": 1,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 272,
   "Task": "Start a conversation with a stranger on public transport",
   "Category": "Relationships",
   "Time": 1,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 273,
   "Task": "Apply to a job that scares you (in a good way)",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 274,
   "Task": "Post your portfolio online and ask for feedback",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 275,
   "Task": "Do a 24-hour challenge of no negative self-talk",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 276,
   "Task": "Go to the cinema alone and stay the whole time",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 277,
   "Task": "Spend a full day doing deep house cleaning",
   "Category": "Chores",
   "Time": 5,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 278,
   "Task": "Host a friend or couple for dinner at your place",
   "Category": "Relationships",
   "Time": 4,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 279,
   "Task": "Go somewhere new by yourself (museum, cafe)",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 280,
   "Task": "Spend one full day tackling your biggest avoidance task",
   "Category": "Other",
   "Time": 5,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 281,
   "Task": "Wake up at 5:30 AM and start your day intentionally",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 282,
   "Task": "Pitch a freelance or consulting service to someone",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 283,
   "Task": "Run 5 km without stopping",
   "Category": "Fitness",
   "Time": 3,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 284,
   "Task": "Spend a whole day offline (no phone, computer, TV)",
   "Category": "Other",
   "Time": 5,
   "Difficulty": "Extra challenging",
   "Status": false,
 },
 {
   "ID": 285,
   "Task": "Write 5 things you're looking forward to",
   "Category": "Mental health",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 286,
   "Task": "Delete one unsued Notion page",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 287,
   "Task": "Dance to a song",
   "Category": "Mental health",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 288,
   "Task": "Take stairs instead of elevator",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 289,
   "Task": "Try some CSS animation",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 290,
   "Task": "Find 3 new houses in Ålesund you like",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 291,
   "Task": "Research one piece of equpiment you want to buy",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 292,
   "Task": "Offer Robin a massage",
   "Category": "Relationships",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 293,
   "Task": "Pick one thing for your dream wedding",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 294,
   "Task": "Research car cage for Bonnie",
   "Category": "Dog",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 295,
   "Task": "Look at IT companies in Ålesund",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 296,
   "Task": "Give Bonnie a massage",
   "Category": "Dog",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 297,
   "Task": "Pick 3 cafes you want to visit",
   "Category": "Other",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 298,
   "Task": "Put on a podcast",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 299,
   "Task": "Pick a new desktop background",
   "Category": "Other",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 300,
   "Task": "Do 1 pistol squat",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 301,
   "Task": "Dust your lego",
   "Category": "Chores",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 302,
   "Task": "Do 30 second active hang",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 303,
   "Task": "Stretch and touch your toes",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Daily Surviving",
   "Status": false,
 },
 {
   "ID": 304,
   "Task": "Try a head stand",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 305,
   "Task": "Do 10 burpees",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 306,
   "Task": "Do 30 second hollow hold + arch hold",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 307,
   "Task": "Do 5 V-ups",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 308,
   "Task": "Do 30 shoulder taps in plank",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 309,
   "Task": "Do 15 calf raises",
   "Category": "Fitness",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 310,
   "Task": "Try to hold crow pose",
   "Category": "Fitness",
   "Time": 1,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 311,
   "Task": "Add one feature to any project",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 312,
   "Task": "Wacth 1 video about UX",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 313,
   "Task": "Plan how to improve old project",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 314,
   "Task": "Research where you could contribute on GitHub",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 315,
   "Task": "Learn something about 1 SQL database",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 316,
   "Task": "Study Python for 1 hour",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Challenging",
   "Status": false,
 },
 {
   "ID": 317,
   "Task": "Deep dive into what each programming language is used for",
   "Category": "IT",
   "Time": 3,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 318,
   "Task": "Watch 1 video about backend",
   "Category": "IT",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 },
 {
   "ID": 319,
   "Task": "Make pinterest board for some spefic topic",
   "Category": "Other",
   "Time": 2,
   "Difficulty": "Normal",
   "Status": false,
 }
];

export default quests;
